---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-dns
  labels:
    app.kubernetes.io/name: internal-dns
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: internal-dns
  template:
    metadata:
      labels:
        app.kubernetes.io/name: internal-dns
    spec:
      serviceAccountName: internal-dns
      containers:
        - name: internal-dns
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --source=service
            - --source=ingress
            - --provider={{ .Values.provider }}
            - --aws-zone-type={{ .Values.awsZoneType }} # only look at private hosted zones (valid values are public, private or no value for both)
            - --registry=txt
            - --txt-owner-id={{ .Values.txtOwnerId }} # unique per cluster id
            - --ingress-class={{ .Values.ingressClass }}
          env:
            - name: AWS_DEFAULT_REGION
              value: {{ .Values.awsRegion }} # change to region where EKS is installed
