# Default values for argo-events.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#

replicaCount: 2

# podDisruptionBudget specifies the disruption budget for the controller pods.
# Disruption budget will be configured only when the replicaCount is greater than 1
podDisruptionBudget:
  minAvailable: 1

nodeSelector: {}
