apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argo-cmd-params-cm
    app.kubernetes.io/part-of: argo
  name: argo-cmd-params-cm
  namespace: argo
data:
  server.secure: "false"