---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: karpenter
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: karpenter
      app.kubernetes.io/instance: karpenter
