{{- if .Values.config.sonar.enabled -}}
{{/*
Any configurations to this specific VPA takes precedence. But fallback to the global setting if not set.
Utilize mergeOverwrite to combine the two dictionaries.
*/}}
{{- $vpa := mergeOverwrite (deepCopy .Values.global.vpa) (.Values.config.sonar.vpa | default dict) -}}
{{- if $vpa.enabled -}}
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "ketch.transponder.sonar.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "ketch.transponder.sonar.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ include "ketch.transponder.sonar.fullname" . }}
  updatePolicy:
    updateMode: "{{ $vpa.updateMode | default "Off" }}"
  resourcePolicy:
    containerPolicies:
      - containerName: sonar
{{- with $vpa.minimumAllowed }}
        minAllowed:
          cpu: {{ .cpu | default "100m" }}
          memory: {{ .memory | default "128Mi" }}
{{- else }}
        minAllowed:
          cpu: 100m
          memory: 128Mi
{{- end }}
{{- with $vpa.maximumAllowed }}
        maxAllowed:
          cpu: {{ .cpu | default "3" }}
          memory: {{ .memory | default "8192Mi" }}
{{- else }}
        maxAllowed:
          cpu: 3
          memory: 8192Mi
{{- end }}
        controlledResources: [ "cpu", "memory" ]
{{- end -}}
{{- end -}}
