{{- if .Values.config.agent.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ketch.transponder.agent.fullname" . }}
  labels: {{ include "ketch.transponder.agent.labels" . | nindent 4 }}
data:
  config.yaml: |
{{- range .Values.config.agent.scripts }}
    {{ .name }}:
      {{ .code }}:
{{- range .providers }}
        - provider: {{ .provider }}
          url: {{ .url }}
{{- end }}
{{- end }}
{{- end -}}
