{{- if .Values.config.agent.enabled -}}
{{- $loggingLevel := .Values.config.agent.loggingLevel | default .Values.config.loggingLevel | default "info" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ketch.transponder.agent.fullname" . }}
  labels: {{ include "ketch.transponder.agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.config.agent.replica }}
  selector:
    matchLabels: {{ include "ketch.transponder.agent.matchLabels" . | nindent 6 }}
  strategy: {{ include "ketch.transponder.deployment.deploymentStrategy" .Values.config.agent.deploymentStrategy | nindent 4 }}
  template:
    metadata:
      labels: {{ include "ketch.transponder.agent.labels" . | nindent 8 }}
    spec:
      imagePullSecrets:
{{- if .Values.imageCredentials.enabled }}
        - name: {{ include "ketch.transponder.fullname" . }}-regcred
{{- end }}
{{- range .Values.global.imagePullSecrets }}
        - name: {{ . }}
{{- end }}
      containers:
        - name: agent
          image: "{{ include "ketch.transponder.agent.image" . }}:{{ (.Values.config.agent.image).tag | default (include "ketch.transponder.version" .) }}"
          imagePullPolicy: {{ (.Values.config.agent.image).pullPolicy | default .Values.global.image.pullPolicy }}
          env:
            - name: AGENT_ENVIRONMENT
              value: "{{ .Values.config.environment | default "production" }}"
            - name: AGENT_APPLIANCE_ID
              value: "{{ .Values.config.id }}"
            - name: AGENT_POLL_INTERVAL
              value: "{{ .Values.config.agent.interval }}"
            - name: AGENT_SCRIPT_CONFIG_PATH
              value: "/app/scripts/config.yaml"
            - name: AGENT_LOGLEVEL
              value: "{{ $loggingLevel }}"
            - name: AGENT_SERVER_MIDDLEWARE_LOGGING_ENABLED
              value: "{{ (.Values.config.agent.accessLogging).enabled | default "true" }}"
            - name: AWS_DEFAULT_REGION
              value: "{{ .Values.config.aws.region | default "us-west-2" }}"
            # Start of Server config
            - name: AGENT_SERVER_BIND
              value: "{{ .Values.config.agent.bind | default "0.0.0.0" }}"
            - name: AGENT_SERVER_LISTEN
              value: "{{ .Values.config.agent.listen | default "5000" }}"
            - name: AGENT_SERVER_TLS_ENABLED
              value: "true"
            - name: AGENT_SERVER_TLS_CERT_FILE
              value: "/tls/{{ include "ketch.transponder.tls.cert.file" .Values.config }}"
            - name: AGENT_SERVER_TLS_KEY_FILE
              value: "/tls/{{ include "ketch.transponder.tls.key.file" .Values.config }}"
            - name: AGENT_SERVER_TLS_INSECURE
              value: "{{ .Values.config.tls.insecure | default "false" }}"
            - name: AGENT_SERVER_TLS_OVERRIDE
              value: "{{ .Values.config.tls.override }}"
{{- if .Values.config.tls.rootca.content }}
            - name: AGENT_SERVER_TLS_ROOTCA_FILE
              value: "/tls/{{ include "ketch.transponder.tls.rootca.file" .Values.config }}"
{{- end }}
            # End of Server config
            # Start of Gateway config
            - name: AGENT_WINDLASS_NAME
              value: "{{ (.Values.config.agent.gateway).name | default "gateway" }}"
            - name: AGENT_WINDLASS_URL
              value: "{{ (.Values.config.agent.gateway).url | default "https://windlass.ketchapi.com" }}"
            - name: AGENT_WINDLASS_TLS_ENABLED
              value: "true"
{{- with (.Values.config.agent.gateway).tls }}
            - name: AGENT_WINDLASS_TLS_INSECURE
              value: "{{ .insecure | default "false" }}"
{{- if .override }}
            - name: AGENT_WINDLASS_TLS_OVERRIDE
              value: "{{ .override }}"
{{- end }}
{{- if .usePrivateCert }}
            - name: AGENT_WINDLASS_TLS_CERT_FILE
              value: "/tls/{{ include "ketch.transponder.tls.cert.file" $.Values.config }}"
            - name: AGENT_WINDLASS_TLS_KEY_FILE
              value: "/tls/{{ include "ketch.transponder.tls.key.file" $.Values.config }}"
{{- if $.Values.config.tls.rootca.content }}
            - name: AGENT_WINDLASS_TLS_ROOTCA_FILE
              value: "/tls/{{ include "ketch.transponder.tls.rootca.file" $.Values.config }}"
{{- end }}
{{- end }}
{{- end }}
            # End of Gateway config
{{- include "ketch.transponder.deployment.env.secretProvider" (dict "context" . "component" "AGENT") | nindent 12 }}
          readinessProbe: {{ include "ketch.transponder.deployment.readinessProbe" (dict "context" . "component" "agent") | nindent 12 }}
          livenessProbe: {{ include "ketch.transponder.deployment.livenessProbe" (dict "context" . "component" "agent") | nindent 12 }}
          volumeMounts:
            - name: tls
              mountPath: /tls
              readOnly: true
            - name: scripts
              mountPath: /app/scripts
              readOnly: true
          resources: {{ include "ketch.transponder.deployment.resources" .Values.config.agent.resources | nindent 12 }}
          securityContext: {{ include "ketch.transponder.deployment.securityContext" .Values.securityContext | nindent 12 }}
      volumes:
        - name: scripts
          configMap:
            name: {{ include "ketch.transponder.agent.fullname" . }}
            items:
              - key: config.yaml
                path: config.yaml
        - name: tls
          projected:
            sources:
{{- include "ketch.transpodner.deployment.volume.server.tls" . | nindent 14 -}}
{{- include "ketch.transponder.deployment.volume.vault.tls" . | nindent 14 -}}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
{{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels: {{ include "ketch.transponder.agent.matchLabels" . | nindent 20 }}
                topologyKey: {{ .Values.podAntiAffinityTopologyKey | default "topology.kubernetes.io/zone" }}
{{- with .Values.affinity }}
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}
      securityContext: {{ include "ketch.transponder.deployment.podSecurityContext" .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "ketch.transponder.agent.serviceAccountName" . }}
{{- end -}}
