{{- if .Values.config.agent.enabled -}}
{{/*
Any configurations to this specific PBD takes precedence. But fallback to the global setting if not set.
Utilize mergeOverwrite to combine the two dictionaries.
*/}}
{{- $pdb := mergeOverwrite (deepCopy .Values.global.podDisruptionBudget) (.Values.config.agent.podDisruptionBudget | default dict) -}}
{{- if $pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ketch.transponder.agent.fullname" . }}
  labels: {{ include "ketch.transponder.agent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "ketch.transponder.agent.matchLabels" . | nindent 6 }}
{{- if $pdb.minAvailable }}
  minAvailable: {{ $pdb.minAvailable }}
{{- end }}
{{- if $pdb.maxUnavailable }}
  maxUnavailable: {{ $pdb.maxUnavailable }}
{{- end }}
{{- end }}
{{- end -}}
