{{- if .Values.config.agent.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ketch.transponder.agent.fullname" . }}
  labels: {{ include "ketch.transponder.agent.labels" . | nindent 4 }}
  annotations:
{{/*
Any annotations added to this specific service takes precedence. But also use the ones added to the global value.
Utilize mergeOverwrite to combine the two dictionaries.
*/}}
{{- $annotations := mergeOverwrite (deepCopy .Values.global.service.annotations) (.Values.config.agent.service.annotations) -}}
{{- toYaml $annotations | indent 4 }}
spec:
  type: {{ (.Values.config.agent.service).type }}
  {{- if and (eq .Values.config.agent.service.type "LoadBalancer") .Values.config.agent.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- toYaml .Values.config.agent.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ (.Values.config.agent.service).port }}
      targetPort: {{ (.Values.config.agent.service).listen | default "5000" }}
      protocol: TCP
      name: https
  selector: {{ include "ketch.transponder.agent.matchLabels" . | nindent 4 }}
{{- end -}}
