{{- if .Values.config.agent.enabled -}}
{{- $create := .Values.global.serviceAccount.create -}}
{{- if hasKey .Values.config.agent.serviceAccount "create" -}}
{{- $create = .Values.config.agent.serviceAccount.create -}}
{{- else if eq .Values.serviceAccount.create false -}}
{{- $create = .Values.serviceAccount.create -}}
{{- end -}}
{{- if $create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ketch.transponder.agent.serviceAccountName" . }}
  labels: {{ include "ketch.transponder.agent.labels" . | nindent 4 }}
  annotations:
{{/*
Any annotations added to this specific serviceAccount takes precedence. But also use the ones added to the global value.
Utilize mergeOverwrite to combine the two dictionaries.
*/}}
{{- $annotations := mergeOverwrite (deepCopy .Values.global.serviceAccount.annotations) (.Values.config.agent.serviceAccount.annotations) -}}
{{- toYaml $annotations | indent 4 -}}
{{- end -}}
{{- end -}}
