apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: 
  name: k8s-events-watcher
subjects:
  - kind: ServiceAccount
    name: k8s-events-watcher
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: k8s-events-watcher
  apiGroup: rbac.authorization.k8s.io