---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-events-watcher
  labels:
    apps: k8s-events-watcher
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: k8s-events-watcher
  template:
    metadata:
      labels:
        app: k8s-events-watcher
    spec:
      serviceAccountName: k8s-events-watcher
      {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
      - name: k8s-events-watcher
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
          - name: K8S_CLUSTER_NAME
            value: "{{ .Values.k8sClusterName }}"
          - name: K8S_ENVIRONMENT
            value: "{{ .Values.k8sEnvironment }}"
          - name: EVENTS_API_ENDPOINT
            value: "{{ .Values.eventsApiEndpoint }}"
        command:
          - watch-k8s-events
        imagePullPolicy: IfNotPresent
        resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
