---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alb-dns
  labels:
    app.kubernetes.io/name: alb-dns
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: alb-dns
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alb-dns
    spec:
      serviceAccountName: alb-dns
      {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
        - name: alb-dns
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --source=service
            - --source=ingress
            - --provider={{ .Values.provider }}
            - --aws-zone-type={{ .Values.awsZoneType }} # only look at public hosted zones (valid values are public, private or no value for both)
            - --registry=txt
            - --txt-owner-id={{ .Values.txtOwnerId }} # unique per cluster id
            - --annotation-filter=kubernetes.io/ingress.class in ({{ .Values.ingressClass }})
          env:
            - name: AWS_DEFAULT_REGION
              value: {{ .Values.awsRegion }} # change to region where EKS is installed
