{{- if .Values.publicIngress.enabled -}}
{{- $ingEnvironment := .Values.publicIngress.environment -}}
{{- $ingClass := .Values.publicIngress.class -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transponder-{{ $ingEnvironment }}-ingress
  labels:
    helm.sh/chart: transponder-2.0.6
    app.kubernetes.io/name: transponder
    app.kubernetes.io/instance: ketch.transponder
    app.kubernetes.io/version: "2.0.6"
    app.kubernetes.io/environment: {{ $ingEnvironment }}
  annotations:
    kubernetes.io/ingress.class: {{ $ingClass }}
spec:
  rules:
    - host: "ketch.{{ $ingEnvironment }}.ncsav3.tech"
      http:
        paths:
          - path: /transponder
            pathType: Prefix
            backend:
              service:
                name: transponder-transponder
                port:
                  number: 443
{{- end }}
