apiVersion: v1
kind: Service
metadata:
  name: op-scim-bridge
  labels:
    app: op-scim-bridge
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: http
  selector:
    app: op-scim-bridge
