{{- if and .Values.podDisruptionBudget (gt (int .Values.replicaCount) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: argocd-applicationset-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: argocd-applicationset-controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-applicationset-controller
  {{- toYaml .Values.podDisruptionBudget | nindent 2 }}
{{- end }}
---
{{- if and .Values.podDisruptionBudget (gt (int .Values.replicaCount) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: argocd-dex-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: argocd-dex-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-dex-server
  {{- toYaml .Values.podDisruptionBudget | nindent 2 }}
{{- end }}
---
{{- if and .Values.podDisruptionBudget (gt (int .Values.replicaCount) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: argocd-notifications-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: argocd-notifications-controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-notifications-controller
  {{- toYaml .Values.podDisruptionBudget | nindent 2 }}
{{- end }}
---
{{- if and .Values.podDisruptionBudget (gt (int .Values.replicaCount) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: argocd-redis
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: argocd-redis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-redis
  {{- toYaml .Values.podDisruptionBudget | nindent 2 }}
{{- end }}
---
{{- if and .Values.podDisruptionBudget (gt (int .Values.replicaCount) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: argocd-repo-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: argocd-repo-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  {{- toYaml .Values.podDisruptionBudget | nindent 2 }}
{{- end }}
---
{{- if and .Values.podDisruptionBudget (gt (int .Values.replicaCount) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: argocd-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: argocd-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
  {{- toYaml .Values.podDisruptionBudget | nindent 2 }}
{{- end }}
---
{{- if and .Values.podDisruptionBudget (gt (int .Values.replicaCount) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: argocd-application-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: argocd-application-controller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-application-controller
  {{- toYaml .Values.podDisruptionBudget | nindent 2 }}
{{- end }}
